import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vuePlugin from "esbuild-plugin-vue3";
import fs from "fs";
import path from "path";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const distDir = "dist";

function copyReleaseFiles() {
	if (!fs.existsSync(distDir)) {
		fs.mkdirSync(distDir, { recursive: true });
	}

	const filesToCopy = [
		{ src: "manifest.json", dest: path.join(distDir, "manifest.json") },
		{ src: "src/styles/styles.css", dest: path.join(distDir, "styles.css") },
	];

	for (const { src, dest } of filesToCopy) {
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, dest);
			console.log(`[copy] ${src} → ${dest}`);
		} else {
			console.warn(`[copy] ${src} not found, skipping`);
		}
	}
}

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [vuePlugin()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: distDir,
	entryNames: "main",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyReleaseFiles();
	await context.dispose();
	process.exit(0);
} else {
	copyReleaseFiles();
	await context.watch();
}
