import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import vuePlugin from "esbuild-plugin-vue3";
import fs from "fs";
import path from "path";

const prod = (process.argv[2] === "production");
const distDir = "dist";

function getBanner() {
	const tdesignCSS = readTDesignCSS();
	return {
		js: `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
${tdesignCSS ? `
(function() {
  var style = document.createElement('style');
  style.textContent = ${JSON.stringify(tdesignCSS)};
  document.head.appendChild(style);
})();
` : ''}
`,
	};
}

function readTDesignCSS() {
	try {
		const projectRoot = process.cwd();
		const styleDir = path.join(projectRoot, 'node_modules/tdesign-mobile-vue/es');

		const components = [
			'button', 'input', 'textarea', 'loading', 'text', 'tabs', 'tab-panel',
			'picker', 'popup', 'cell', 'cell-group', 'checkbox', 'progress', 'result',
			'segmented-control', 'empty', 'overlay', 'space', 'divider', 'badge'
		];

		let allCSS = '';
		for (const comp of components) {
			const cssPath = path.join(styleDir, comp, 'style', 'index.css');
			if (fs.existsSync(cssPath)) {
				allCSS += fs.readFileSync(cssPath, 'utf-8') + '\n';
			}
		}

		const mainCSS = path.join(styleDir, 'style', 'index.css');
		if (fs.existsSync(mainCSS)) {
			allCSS = fs.readFileSync(mainCSS, 'utf-8') + '\n' + allCSS;
		}

		console.log('[esbuild] Read TDesign CSS for components:', components.join(', '));
		return allCSS;
	} catch (e) {
		console.warn('[esbuild] TDesign CSS not found:', e.message);
		return '';
	}
}

function copyReleaseFiles() {
	if (!fs.existsSync(distDir)) {
		fs.mkdirSync(distDir, { recursive: true });
	}

	const filesToCopy = [
		{ src: "manifest.json", dest: path.join(distDir, "manifest.json") },
		{ src: "src/styles/styles.css", dest: path.join(distDir, "styles.css") },
	];

	for (const { src, dest } of filesToCopy) {
		if (fs.existsSync(src)) {
			fs.copyFileSync(src, dest);
			console.log(`[copy] ${src} → ${dest}`);
		} else {
			console.warn(`[copy] ${src} not found, skipping`);
		}
	}
}

const context = await esbuild.context({
	banner: getBanner(),
	entryPoints: ["src/main.ts"],
	bundle: true,
	plugins: [vuePlugin()],
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	outdir: distDir,
	entryNames: "main",
	minify: prod,
});

if (prod) {
	await context.rebuild();
	copyReleaseFiles();
	await context.dispose();
	process.exit(0);
} else {
	copyReleaseFiles();
	await context.watch();
}
